name: ptgp-test
channels:
    - conda-forge
dependencies:
    - python>=3.12
    - numpy
    - pymc
    - pytensor>=3.0.2
    - pytest
    - mypy
    - polars
    - scipy
    - filelock
    - numba
    - setuptools
    - cons
    - etuples
    - logical-unification
    - minikanren
    - arviz
    - cachetools
    - cloudpickle
    - pandas
    - rich
    - threadpoolctl
    - typing_extensions
    - pip
    - pip:
        - jax
        - jaxlib
        - optax
        - gpjax
