name: ptgp-test
channels:
    - conda-forge
dependencies:
    - python>=3.12
    - jax
    - jaxlib
    - optax
    - numpy
    - pytest
    - gpjax
    - pip
    - pip:
        - git+https://github.com/jessegrabowski/pytensor@assumption-system
        - git+https://github.com/pymc-devs/pymc@main
