name: ptgp
channels:
    - conda-forge
dependencies:
    - python>=3.12
    - pymc
    - pytensor>=3.0.2
    - jax
    - jaxlib
    - optax
    - scipy
    - pytest
    - gpjax
    - ipykernel
    - ipywidgets
    - ipympl
    - matplotlib
    - seaborn
    - pandas
    - scikit-learn
    - pre-commit
    - pytest
    - arviz
    - pip
