name: pytest

on:
  pull_request:
  push:
    branches: [main]
    paths:
      - ".github/workflows/*"
      - "ptgp/**"
      - "tests/**"
      - "pyproject.toml"
      - "conda_envs/**"

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.13"
            shell: bash -leo pipefail {0}
          - os: windows-latest
            python-version: "3.12"
            shell: cmd /C call {0}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2.0.7
        with:
          environment-file: conda_envs/environment-test.yaml
          create-args: >-
            python=${{ matrix.python-version }}
          environment-name: ptgp-test
          init-shell: ${{ matrix.os == 'windows-latest' && 'cmd.exe' || 'bash' }}
          cache-environment: true
          post-cleanup: none
      - name: Install ptgp
        run: |
          pip install -e . --no-deps
          python --version
          pip check
      - name: Run tests
        run: |
          python -m pytest --color=yes -vv --durations=50 tests/
